//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECTADM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ADMEntities : DbContext
    {
        public ADMEntities()
            : base("name=ADMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<contabilidad> contabilidads { get; set; }
        public virtual DbSet<cotizacione> cotizaciones { get; set; }
        public virtual DbSet<factura> facturas { get; set; }
        public virtual DbSet<inventario> inventarios { get; set; }
        public virtual DbSet<ordenesCompra> ordenesCompras { get; set; }
        public virtual DbSet<productos_Cotizaciones> productos_Cotizaciones { get; set; }
        public virtual DbSet<productos_factura> productos_factura { get; set; }
        public virtual DbSet<productos_OrdenesCompra> productos_OrdenesCompra { get; set; }
        public virtual DbSet<proveedore> proveedores { get; set; }
    }
}
