//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECTADM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cotizacione()
        {
            this.productos_Cotizaciones = new HashSet<productos_Cotizaciones>();
        }
    
        public int Id_cotizacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> Monto { get; set; }
        public Nullable<int> Impuestos { get; set; }
        public Nullable<int> Monto_total { get; set; }
        public string Tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos_Cotizaciones> productos_Cotizaciones { get; set; }
    }
}
