//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECTADM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ADMEntities3 : DbContext
    {
        public ADMEntities3()
            : base("name=ADMEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<FacturaCotizacion_Result> FacturaCotizacion(Nullable<int> id_cotizacion)
        {
            var id_cotizacionParameter = id_cotizacion.HasValue ?
                new ObjectParameter("Id_cotizacion", id_cotizacion) :
                new ObjectParameter("Id_cotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FacturaCotizacion_Result>("FacturaCotizacion", id_cotizacionParameter);
        }
    
        public virtual ObjectResult<FacturaCotizacion2_Result> FacturaCotizacion2(Nullable<int> id_cotizacion)
        {
            var id_cotizacionParameter = id_cotizacion.HasValue ?
                new ObjectParameter("Id_cotizacion", id_cotizacion) :
                new ObjectParameter("Id_cotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FacturaCotizacion2_Result>("FacturaCotizacion2", id_cotizacionParameter);
        }
    
        public virtual ObjectResult<FacturaCotizacion3_Result> FacturaCotizacion3(Nullable<int> id_cotizacion)
        {
            var id_cotizacionParameter = id_cotizacion.HasValue ?
                new ObjectParameter("Id_cotizacion", id_cotizacion) :
                new ObjectParameter("Id_cotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FacturaCotizacion3_Result>("FacturaCotizacion3", id_cotizacionParameter);
        }
    
        public virtual ObjectResult<FacturaOrdenes_Result> FacturaOrdenes(Nullable<int> id_Orden_compra)
        {
            var id_Orden_compraParameter = id_Orden_compra.HasValue ?
                new ObjectParameter("Id_Orden_compra", id_Orden_compra) :
                new ObjectParameter("Id_Orden_compra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FacturaOrdenes_Result>("FacturaOrdenes", id_Orden_compraParameter);
        }
    
        public virtual ObjectResult<Facturaordenes2_Result> Facturaordenes2(Nullable<int> id_Orden_compra)
        {
            var id_Orden_compraParameter = id_Orden_compra.HasValue ?
                new ObjectParameter("Id_Orden_compra", id_Orden_compra) :
                new ObjectParameter("Id_Orden_compra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Facturaordenes2_Result>("Facturaordenes2", id_Orden_compraParameter);
        }
    
        public virtual ObjectResult<Facturaordenes3_Result> Facturaordenes3(Nullable<int> id_Orden_compra)
        {
            var id_Orden_compraParameter = id_Orden_compra.HasValue ?
                new ObjectParameter("Id_Orden_compra", id_Orden_compra) :
                new ObjectParameter("Id_Orden_compra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Facturaordenes3_Result>("Facturaordenes3", id_Orden_compraParameter);
        }
    }
}
