//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECTADM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_OrdenesCompra
    {
        public int Id_producto_orden_compra { get; set; }
        public Nullable<int> Id_producto { get; set; }
        public Nullable<int> Id_ordenesDeCopras { get; set; }
        public string Cantidad { get; set; }
    
        public virtual inventario inventario { get; set; }
        public virtual ordenesCompra ordenesCompra { get; set; }
    }
}
